---
title: 'Urban Big Data Analytics - Group Session 1: Gapminder'
author: "Andy Hong"
date: "July 18, 2018"
output:
  pdf_document: default
  html_document:
    css: my_styles.css
  word_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Prerequisites

* Go to Gapminder: https://www.gapminder.org/tools

* Please watch the instruction first: https://vimeo.com/231885967


## Instruction

### 1. Synopsis
The purpose of this grop session is to have you go through the basic steps to tell **a story**. You will explore a fascinating data set put together by **Gapminder**. The data set ranges from child mortality to CO2 emissions for all the coutries where data are available. We will explore several key indicators of health, demographics, and the environment, and have you go through **5 steps** to tell a good story.

### 2. Each group is assigned two indicators to explore
 + Group 1: Income x Life expectancy
 + Group 2: Income x Life expectancy
 + Group 3: Income x CO2
 + Group 4: Income x CO2
 + Group 5: Income x Babies per woman
 + Group 6: Income x Babies per woman
 + Group 7: Income x Child mortality
 + Group 8: Income x Child mortality

### 3. Each indicator represents one issue
 + **Life expectancy** is about health and wealth
 + **CO2 emission** is about the environment and sustainability
 + **Babies per woman** is about welfare and women's rights
 + **Child mortality** is about health and welfare

### 4. Tell a story using the GapMinder tool

### 5. A good story consists of five elements: 
  + **Issue at hand**: What is the issue? Is it about health, the environment, or the welfare system?
  + **Cause and effect**: What is the relationship between income and the indicator you are assigned to? Does the line go up or down or stay the same?
  + **Supporting data**: Usually you will need to find the data to explore the issue, but you are given the Gapminder tool, so you don't need to worry about it.
  + **Interprtation**: Why do you think that relationship exist? Do some research. Search the news and use your common sense and your own experience to explain the relationship
  + **Summary and conclusions**: Summarize what you've learned and give a short conclusion. 


## Tell your story

 + Pick one person in your group to present your story. Each group has three minutes to present.
 + Use the **air plane** icon on the upper right corner of the gapminder tool.  
 + Copy the shortened link and send it to the instructor (andyhong@gmail.com). Please use the following email title format: <br>
 `VSP BigData [lecture number] - [group number] - [presenter name]` <br>
 ex), `VSP BigData Lecture 1 - Group 1 - Andy Hong` <br>
 

<br><br><br>


 
 




